<?php
/**
 * 分类管理
 * @author pawn
 * @date 2017年11月28日12:24:36
 */
namespace backend\modules\category;

use yii\base\Module;

class Category extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}