<?php
/**
 * 工具类
 * @author pawn
 * @date 2017年7月17日21:28:52
 */
namespace backend\modules\Tool;

use yii\base\Module;

class Tool extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}