<?php
/**
 * 用户管理模块
 * @author pawn
 * @date 2017年11月29日17:54:33
 */
namespace frontend\modules\Members;

use yii\base\Module;

class Members extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}