<?php
/**
 * 博客模型
 * @author pawn
 * @date 2017年8月11日18:07:23
 */
namespace backend\modules\Article;

use yii\base\Module;

class Article extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}