<?php
/**
 * 模块配置文件
 * @author pawn
 * @date 2017年5月7日17:41:57
 */
namespace frontend\modules\Article;

use yii\base\Module;

class Article extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}