<?php
/**
 * @author pawn
 * @date
 */

namespace backend\modules\Members;

use yii\base\Module;

class Members extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}